apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-app-deployment
  labels:
    app: server-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server-app
  template:
    metadata:
      labels:
        app: server-app
    spec:
      containers:
      - name: server-app-container
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000
        env:
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo_url
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password


---

apiVersion: v1
kind: Service
metadata:
  name: server-app-service
spec:
  type: NodePort
  selector:
    app: server-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
      nodePort: 30008
