apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-sol2-deployment
  namespace: sol-2
  labels:
    app: server-sol2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server-sol2
  template:
    metadata:
      labels:
        app: server-sol2
    spec:
      containers:
      - name: python-ms-sol2
        image: python-ms-sol2:lastest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: redis-config-sol2
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: redis-config-sol2
              key: REDIS_PORT

---

apiVersion: v1
kind: Service
metadata:
  name: server-sol2-service
spec:
  type: NodePort
  selector:
    app: server-sol2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
      nodePort: 30008
