apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-sol1-deployment
  namespace: sol-1
  labels:
    app: server-sol1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server-sol1
  template:
    metadata:
      labels:
        app: server-sol1
    spec:
      containers:
      - name: python-ms-sol1
        image: python-ms-sol1:lastest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: redis-config-sol1
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: redis-config-sol1
              key: REDIS_PORT
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP

---

apiVersion: v1
kind: Service
metadata:
  name: server-sol1-service
spec:
  type: NodePort
  selector:
    app: server-sol1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
      nodePort: 30008
